name: .NET Core

on:
  push:
    branches: [ master,dev ] 
  pull_request:
    branches: [ master ] 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: show path
      run: pwd
    - name: Install dependencies
      run: pwd
           dotnet restore .\framework\Volo.Abp.sln 
    - name: Build
      run: pwd
           dotnet build .\framework\Volo.Abp.sln  --configuration Release --no-restore 
    - name: Test
      run: pwd
          dotnet test .\framework\Volo.Abp.sln  --no-restore --verbosity normal 
