name: .NET Core

on:
  push:
    branches: [ master,dev ] 
  pull_request:
    branches: [ master ] 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
      working-directory: .\framework
    - name: Build
      run: dotnet build Volo.Abp.sln --configuration Release --no-restore
      working-directory: .\framework
    - name: Test
      run: dotnet test Volo.Abp.sln --no-restore --verbosity normal
      working-directory: .\framework
